### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by pedsm** [Kuldeeplanghani/Fifa-World-Cup-2018#1]
As is you cannot make a fetch request from a browser on a different domain, this prevents web front ends from accessing this data unless they have a dedicated backend that re-routes the API.

This can be done by simply adding a response header `Access-Control-Allow-Origin: *` for more information you can refer to [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

I would personally make a pull request for this but unfortunately, I am not very familiar with Django.

**Comment by Kuldeeplanghani** [comment]
Hi @pedsm,
Thank you for pointing out this, I have fixed it, It will accept all host from now on.
I usually use Django rest's default API View but for I preferred not to.
Anyways Thanks :)
