### ISSUE TITLE
results for knockout games

### ISSUE THREAD

**Issue by lulusanders84** [Kuldeeplanghani/Fifa-World-Cup-2018#2]
Hello,
Thank you so much for your wonderful FIFA World Cup API!
I was wondering how to access the results for the knockout games once they have been played? Each of the group stage fixtures has a link for to the live score endpoint, but the knockout games do not. Also once a knockout game has been played it is not in the data object anymore. 

Thanks,
Lucy Sanders

**Comment by Kuldeeplanghani** [comment]
Hi Lucy,
Thanks for your appreciation. This issue has been fixed.

**Comment by lulusanders84** [comment]
Thanks so much!
